---
title: "Getting started"
code-annotations: hover
---

```{python}
#| echo: false

from helpers import include_shiny_folder, problem_tabs, multiple_choice_app, Quiz

```
# Goal 

The goal of this section is to learn what you need to do to stand up a Shiny application.
Don't worry if you don't really understand how the framework works, or why it's designed in a particular way. 
All we're tryign to do at this stage is to get something working, and become comfortable with the development pattern.


# Create an app

Shiny apps are divided into two parts.
The app *UI* consists of various input and output components, and the *server* expresses how those inputs and outputs should interact. 

Let's start by creating a basic shiny app
To do this you can call `shiny create .` in a project folder, or open up `apps/basic-app/app.py` in the repo. 
This is the simplest possible Shiny application with one input and one output. 

#### 
```{python}
#| echo: false
#| output: asis

include_shiny_folder("apps/examples/1.0-basic-app")
```

There are a four important features that your code needs to have to generate a working Shiny app. 

### 1) UI structure

The Shiny UI is defined with a set of nested function calls. 
You typically start with a container function like `ui.page_fluid()` and then add inputs like `ui.input_slider` and outputs like `ui.output_text_verbatim`.

Inputs and outputs have an `id` value which allows you to refer to their values in the `server` function. 
In this simple example the slider `id` is `"n"` and the output id is `"txt"`.

### 3) Output decorators
The server function defines how your app should calculate outputs for a given set of inputs. 
To do this, you write a function inside the main `server` function which has the same name as the output key, and add two decorators. 
`@output` tells Shiny that the function is an output, and `@render.text` tells it the output type. 
So to fill in the logic for the `txt` output we write:

```{.python}
@output                                     # <1>
@render.text                                # <2>
def txt():                                  # <3>
    return f"n*2 is {input.n() * 2}"
```
1. Identify that this function is an output
2. Define output type
3. Function name connects it to output id

### 4) How to refer to inputs

Shiny is a reactive framework which means that it recalculates an output if and only if its inputs change. 
We'll learn more about reactivity in the next section, but for now
You identify these inputs by calling the attribute of the `input` object which corresponds with a particular input id. 
In this case to refer to `n` we call it with `input.n()`
 
::: callout-tip
Note that inputs are called with `()` so it's `input.n()` not `input.n`
:::

# Improving the app

The basic app created by shiny is not terribly interesting, so instead we're going to work with the [palmer penguins](https://github.com/mcnakhaee/palmerpenguins) data to include a data table and a couple of plots. 
To include a table we need to use a different output function and rendering decorator, but otherwise it works the same. 

::: callout-tip
When reading in data it's usually good to use pathlib `Path(__file__).parent` to reference the data relative to the current file. 
This makes it easier to call `shiny run` from other direcotries without error.
::::

```{python}
#| echo: false
#| output: asis

include_shiny_folder("apps/examples/1.1-table-only")
```

All of the inputs and outputs are documented with interactive examples on the Shiny for Python [reference page](https://shiny.rstudio.com/py/api/), it's a good 

#### Quiz 1.0
```{python}
# | echo: false
# | output: asis

questions = Quiz(
    {
        "What ui input is used for plots?": {
            "choices": ["ui.input_plot", "ui.plot_input", "ui.plotInput"],
            "answer": "ui.input_plot",
        },
        "What rendering decorator is used for images?": {
            "choices": ["@render.image", "@ui.render.image", "@render.Image"],
            "answer": "@render.image"
        },
        "What should you use to collect multiple checkbox reponses?": {
            "choices": ["ui.input.checkbox", "ui.checkbox_group", "ui.radio_buttons"],
            "answer": "ui.checkbox_group",
        },
    }
)

multiple_choice_app(questions)
```

## Add an input

In order to create an interactive app, we need to add an input which the user can manipulate. 
Let's add a `ui.input_slider` widget which let the user select the minimum body mass to include in the table. 
To do this we need to do two things:

1) Add the `ui.input_slider` function to the ui code 
2) Use the value of that code in the rendering function which generates the table.

::: callout-warning
Be careful of mutability when manipulating objects in a data frame. 
Use `.copy` to make sure that you're not changing the original object.
:::

```{python}
#| echo: false
#| output: asis

include_shiny_folder("apps/examples/1.3-table-input-slider")
```

## Add a plot

We can add a plot to the app in the same way that we added a table. 
The steps are:
1) Add `ui.output_plot()` to the ui
2) Add a function whose name matches the id of the output 
3) Decorate that function with `@output` and `@reactive.plot`

```{python}
#| echo: false
#| output: asis

include_shiny_folder("apps/examples/1.4-table-graph-input-slider")
```

# Exercise

1) Add a second plot output to the apps which shows a scatter plot of Bill Depth to Bill Length, there's a plotting function in `plots.py` which provides one implementation.

2) Add a checkbox which adds a line of best fit to the plot. 


```{python}
#| echo: false
#| output: asis

problem_tabs("apps/problem-sets/1.5-add-plot")
```

# Summary

In this section you learned the three main things you need to do to get your Shiny app to run:
- Add inputs and outputs to the UI
- Add server functions which are decorated with @output and @render
- Refer to inputs within server funtions with `input.<id>()`

Next we'll learn what shiny does to make this all work